### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by MartinsVision** [eracknaphobia/script.nhlscores#5]
Been offline for a month  now 😪 Is there anyway to get an update?

**Comment by EricGatesIT** [comment]
Looks like the [api has changed](https://gitlab.com/dword4/nhlapi/-/blob/master/new-api.md), I will have to see if I can convert it to the new api.

**Comment by eracknaphobia** [comment]
This should be fixed now as of version [2023.12.27](https://github.com/eracknaphobia/script.nhlscores/releases/tag/v2023.12.27).
